# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90b96a9e8f6d6c9bfb35bb5559cacaf8a0f424cf8729ef5523ecd0e807b241a77527f98974b1258da95f0378d3ad255bad771604080d013f8a1ae2cc6124c548

test:
  secret_key_base: 8f8d51f47a00432e7c062a8d44fe2661657a9695c528bbdf947cd76030c33b1cf13bb791e07d0717c284f58f62de1aefaf9339dac2925d5816042fd5b4300e4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
